# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Eduard F. Martínez González
email: efmartinez@icesi.edu.co
description: > # this means to ignore newlines until "url:"
  Personal website of Eduard F. Martínez González, Ph.D. in Economics. 
  Professor at Universidad Icesi and Director of the Center for Research in Economics and Finance (CIENFI).
footer_text: > #
  © 2025 Eduard F. Martínez González. All rights reserved.

url: "https://eduard-martinez.github.io"
baseurl: "" # leave empty for root
last_updated: October 2025 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: eduard-martinez
twitter_username: eduardmartinezg
linkedin_username: eduard-martinez-gonzalez
scholar_authorid: 8dfzZ3sAAAAJ # (tu Google Scholar ID)
contact_note: >
  You can reach me at efmartinez{at}icesi.edu.co or visit my research center at <a href="https://www.icesi.edu.co/cienfi" target="_blank">CIENFI</a>.

google_analytics: # UA-XXXXXXXXX # optional: your Google Analytics code

# Tags
tag_dir: tag

# Edit SASS
sass:
    sass_dir: _sass

# -----------------------------------------------------------------------------
# Site navigation
# -----------------------------------------------------------------------------
nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Projects"
    url: "/projects/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "About"
    url: "/about/"

# -----------------------------------------------------------------------------
# Pagination
# -----------------------------------------------------------------------------
#paginate: 8
#permalink: /articles/:year/:title/
#paginate_path: /articles/page:num/

#text:
#  pagination:
#    newer: 'Newer'
#    older: 'Older'

# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------
disqus_shortname: # leave empty unless you configure Disqus

# -----------------------------------------------------------------------------
# Optional features
# -----------------------------------------------------------------------------
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes
include: ['_pages']

# Gems
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.11.1"
anchorjs_version: "3.2.2"